# conf/config.yaml
data:
  raw_dir: data/raw
  processed_dir: data/3_Gold/incidences_normalized.parquet

defaults:
  - _self_
  - model: default    # This loads the model configuration from the model config group.
  - env: prod
  - codecarbon: codecarbon_config.yaml